# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AgroTool_ColorSegmenter
                                 A QGIS plugin
 Precision agriculture application. This plug-in segments the raster layer based on a color distribution calculated from a shape file or a cropped image over the raster layer. (In development)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Syddansk Universitet
        email                : aqu@mmmi.sdu.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog
from qgis.core import QgsRasterLayer, QgsProcessingException, QgsApplication, QgsProject, QgsTask, QgsMessageLog, Qgis
from osgeo import gdal
from PyQt5.QtCore import QThreadPool, pyqtSignal

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .AgroTool_ColorSegmenter_dialog import AgroTool_ColorSegmenterDialog
import os.path
import time
import sys
import inspect
import numpy as np

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

from .Segmenter import colormodels, tiler, segmenter, segmenter_thread2
from .Segmenter.main import SegmentationTask

class SegmentationTask_dev(QgsTask):
    # Define custom signals to update progress and deliver the result
    progress_signal = pyqtSignal(int)
    result_ready = pyqtSignal(np.ndarray)
    def __init__(self, param, description="Segmentation Task"):
        super().__init__(description, QgsTask.CanCancel)
        self.param = param

    def run(self):
        global start_time
        start_time = time.time()
        try:
            thread_pool = QThreadPool().globalInstance()  # Create pool of Thread
            thread_pool.setMaxThreadCount(os.cpu_count())  # Set number of cpu count

            # Initialize the color model using reference pixels
            referencepixels = colormodels.get_referencepixels(self.param)
            colormodel = colormodels.initialize_colormodel(referencepixels, self.param)
            cbs = segmenter.ColorBasedSegmenter(colormodel, self.param)
            self.progress_signal.emit(20)  # 20% progress

            if self.param.tile_processing:
                # For tile processing, generate tile list and manager
                tile_list, tile_manager = tiler.get_tilelist_gdal(thread_pool, self.param)
                self.progress_signal.emit(40)  # 40% progress
                cbs.apply_colormodel_multi_tiles(tile_list)

                # cbs = segmenter_thread2.ColorBasedSegmenter(tile_list, colormodel, self.param)
                # cbs.apply_colormodel_multi_tiles_thread(thread_pool)
                self.progress_signal.emit(80)  # 80% progress
                distance_image = tile_manager.get_distance_raster()
            else:
                # For single-tile processing
                single_tile = tiler.get_single_tile(self.param)
                self.progress_signal.emit(40)  # 40% progress
                cbs.apply_colormodel_single_tile(single_tile)
                self.progress_signal.emit(80)  # 80% progress
                distance_image = np.squeeze(single_tile.distance_img)

            self.progress_signal.emit(90)  # 90% progress

            QgsMessageLog.logMessage("Segmentation task finished successfully.", "AgroTool Color Segmenter", level=Qgis.Info)

            
            # end_time = time.time()
            # minutes = int((end_time - start_time) // 60)
            # seconds = int((end_time - start_time) % 60)
            # QgsMessageLog.logMessage(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter", level=Qgis.Info)
            # print(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter")
            self.result_array = distance_image
            self.result_ready.emit(distance_image)

        except Exception as e:
            QgsMessageLog.logMessage("Error during segmentation: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
            return False  # Indicate failure

        return True  # Indicate success

    def finished(self, result):
        """
        This method is called in the main thread after run() completes.
        It handles saving the result and adding the raster layer to QGIS.
        """
        if result:
            QgsMessageLog.logMessage("Segmentation task finished successfully - Storing results.", "AgroTool Color Segmenter", level=Qgis.Info)
            try:
                # Create output raster layer:
                # Extract raster information using GDAL
                input_ds = gdal.Open(self.param.input_raster_layer.source())
                if input_ds is None:
                    raise RuntimeError("Failed to open input raster with GDAL.")

                # Get raster geotransform and dimensions
                geotransform = input_ds.GetGeoTransform()  # (x_min, pixel_width, 0, y_max, 0, -pixel_height)
                #x_min, pixel_width, _, y_max, _, pixel_height = geotransform
                x_res = input_ds.RasterXSize  # Number of pixels in the x-direction
                y_res = input_ds.RasterYSize  # Number of pixels in the y-direction

                print('Original ortho x and y size: ', x_res, y_res)
                # Create the output raster using the same dimensions, geotransform, and projection
                driver = gdal.GetDriverByName('GTiff')
                #output_ds = driver.Create('/vsimem/temp_raster', x_res, y_res, 1, gdal.GDT_Byte)
                output_ds = driver.Create(self.param.output_file_path, x_res, y_res, 1, gdal.GDT_Byte)
                if output_ds is None:
                    raise RuntimeError("Failed to create output raster.")

                output_ds.SetGeoTransform(geotransform)  # Set the same geotransform as the input raster
                output_ds.SetProjection(input_ds.GetProjection())  # Use the same projection as the input raster

                # Save result: write array to raster and build overviews
                band = output_ds.GetRasterBand(1)
                band.SetNoDataValue(0)
                band.WriteArray(self.result_array) # Build pyramids (overviews) for the raster
                gdal.SetConfigOption("COMPRESS_OVERVIEW", "LZW")  # Optional: Compression for overviews
                output_ds.BuildOverviews("AVERAGE", [2, 4, 8, 16, 32, 64, 128])
                band.FlushCache()

                # Create a QgsRasterLayer from the in-memory raster
                output_name, _ = os.path.splitext(os.path.basename(self.param.output_file_path))
                output_raster_layer = QgsRasterLayer(output_ds.GetDescription(), output_name, "gdal")

                if not output_raster_layer.isValid():
                    raise RuntimeError("Failed to create QgsRasterLayer from in-memory raster.")

                QgsProject.instance().addMapLayer(output_raster_layer)
                
                QgsMessageLog.logMessage("Segmentation completed and added to QGIS.", "AgroTool Color Segmenter", level=Qgis.Info)

                end_time = time.time()
                minutes = int((end_time - start_time) // 60)
                seconds = int((end_time - start_time) % 60)
                QgsMessageLog.logMessage(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter", level=Qgis.Info)
                print(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter")   
            except Exception as e:
                QgsMessageLog.logMessage("Error while saving result: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
        else:
            QgsMessageLog.logMessage("Segmentation task failed.", "AgroTool Color Segmenter", level=Qgis.Critical)
        return

def run_segmentation_task(param):
    """
    Helper function to launch the segmentation task.
    The returned task object can be used to monitor progress or check for errors.
    """
    task = SegmentationTask(param)
    QgsApplication.taskManager().addTask(task)
    return task

def handle_result(param, distance_image):
    global start_time
    try:

        # Create output raster layer:
        # Extract raster information using GDAL
        input_ds = gdal.Open(param.input_raster_layer.source())
        if input_ds is None:
            raise RuntimeError("Failed to open input raster with GDAL.")

        # Get raster geotransform and dimensions
        geotransform = input_ds.GetGeoTransform()  # (x_min, pixel_width, 0, y_max, 0, -pixel_height)
        #x_min, pixel_width, _, y_max, _, pixel_height = geotransform
        x_res = input_ds.RasterXSize  # Number of pixels in the x-direction
        y_res = input_ds.RasterYSize  # Number of pixels in the y-direction

        print('Original ortho x and y size: ', x_res, y_res)
        # Create the output raster using the same dimensions, geotransform, and projection
        driver = gdal.GetDriverByName('GTiff')
        #output_ds = driver.Create('/vsimem/temp_raster', x_res, y_res, 1, gdal.GDT_Byte)
        output_ds = driver.Create(param.output_file_path, x_res, y_res, 1, gdal.GDT_Byte)
        if output_ds is None:
            raise RuntimeError("Failed to create output raster.")

        output_ds.SetGeoTransform(geotransform)  # Set the same geotransform as the input raster
        output_ds.SetProjection(input_ds.GetProjection())  # Use the same projection as the input raster

        # Save result: write array to raster and build overviews
        band = output_ds.GetRasterBand(1)
        band.SetNoDataValue(0)
        band.WriteArray(distance_image) # Build pyramids (overviews) for the raster
        gdal.SetConfigOption("COMPRESS_OVERVIEW", "LZW")  # Optional: Compression for overviews
        output_ds.BuildOverviews("AVERAGE", [2, 4, 8, 16, 32, 64, 128])
        band.FlushCache()

        # Create a QgsRasterLayer from the in-memory raster
        output_name, _ = os.path.splitext(os.path.basename(param.output_file_path))
        output_raster_layer = QgsRasterLayer(output_ds.GetDescription(), output_name, "gdal")

        if not output_raster_layer.isValid():
            raise RuntimeError("Failed to create QgsRasterLayer from in-memory raster.")

        QgsProject.instance().addMapLayer(output_raster_layer)
        
        QgsMessageLog.logMessage("Segmentation completed and added to QGIS.", "AgroTool Color Segmenter", level=Qgis.Info)

        end_time = time.time()
        minutes = int((end_time - start_time) // 60)
        seconds = int((end_time - start_time) % 60)
        QgsMessageLog.logMessage(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter", level=Qgis.Info)
        print(f"Total processing time: {minutes} min {seconds} sec", "AgroTool Color Segmenter")
    
    except Exception as e:
        QgsMessageLog.logMessage("Error while saving result: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
            

def segment_main(param, output_raster):

    thread_pool = QThreadPool().globalInstance()  # Create pool of Thread
    thread_pool.setMaxThreadCount(os.cpu_count())  # Set number of cpu count

    # Initialize the color model using reference pixels
    referencepixels = colormodels.get_referencepixels(param)
    colormodel = colormodels.initialize_colormodel(referencepixels, param)
    cbs = segmenter.ColorBasedSegmenter(colormodel, param)

    if param.tile_processing:
        # For tile processing, generate tile list and manager
        tile_list, tile_manager = tiler.get_tilelist_gdal(thread_pool, output_raster, param)
        cbs.apply_colormodel_multi_tiles(tile_list)

        # cbs = segmenter_thread2.ColorBasedSegmenter(tile_list, colormodel, self.param)
        # cbs.apply_colormodel_multi_tiles_thread(thread_pool)
        distance_image = tile_manager.get_distance_raster()
    else:
        # For single-tile processing
        single_tile = tiler.get_single_tile(param)
        cbs.apply_colormodel_single_tile(single_tile)
        distance_image = np.squeeze(single_tile.distance_img)
    
    try:

        # Save result: write array to raster and build overviews
        band = output_raster.GetRasterBand(1)
        band.SetNoDataValue(0)
        band.WriteArray(distance_image) # Build pyramids (overviews) for the raster
        gdal.SetConfigOption("COMPRESS_OVERVIEW", "LZW")  # Optional: Compression for overviews
        output_raster.BuildOverviews("AVERAGE", [2, 4, 8, 16, 32, 64, 128])
        band.FlushCache()

        # Create a QgsRasterLayer from the in-memory raster
        output_name, _ = os.path.splitext(os.path.basename(param.output_file_path))
        output_raster_layer = QgsRasterLayer(output_raster.GetDescription(), output_name, "gdal")

        if not output_raster_layer.isValid():
            raise RuntimeError("Failed to create QgsRasterLayer from in-memory raster.")

        QgsProject.instance().addMapLayer(output_raster_layer)
        
        QgsMessageLog.logMessage("Segmentation completed and added to QGIS.", "AgroTool Color Segmenter", level=Qgis.Info)
    except Exception as e:
        QgsMessageLog.logMessage("Error while saving result: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
    



class AgroTool_ColorSegmenter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AgroTool_ColorSegmenter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AgroTool Color Segmenter')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.active_tasks = []

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AgroTool_ColorSegmenter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        #icon_path = ':/plugins/AgroTool_ColorSegmenter/icon.png'
        icon_path = os.path.join(os.path.join(cmd_folder, 'icon.png'))
        #icon_path = ':\plugins\\agrotool_colorsegmenter\icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AgroTool Color Segmenter'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AgroTool Color Segmenter'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = AgroTool_ColorSegmenterDialog()

        # show the dialog
        self.dlg.show()

        # Run the dialog event loop
        result = self.dlg.exec_()

        # See if OK was pressed
        if result == QDialog.Accepted:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            print()
            print('LOADED PARAMETERS')
            print('Input raster: ', self.dlg.input_raster_layer)
            print('Output raster: ', self.dlg.output_file_path)
            print('RefPixel Method: ', self.dlg.refPixel_method)
            print('Shape File: ', self.dlg.shape_file)
            print('Ref Image path: ', self.dlg.ref_image_path)
            print('Ref Mask path: ', self.dlg.ref_pixel_maks_path)

            print('Metric: ', self.dlg.distance_metric)
            print('Number of components: ', self.dlg.gmm_components)
            print('Scale factor: ', self.dlg.scale_factor)

            print('Tile processing: ', self.dlg.tile_processing)
            print('Tile width: ', self.dlg.tiles_width)
            print('Tile height: ', self.dlg.tiles_height)
            print('Tiles save: ', self.dlg.save_tiles)
            print('Tiles distace save: ', self.dlg.save_tiles_distance)
            print('Tiles save dir: ', self.dlg.save_tiles_path)

            # Parameters validation
            # Verify if valid raster layer
            if not self.dlg.input_raster_layer.isValid():
                raise QgsProcessingException(self.tr('Unvalid input raster layer.'))

            if self.dlg.refPixel_method == 0:
                if not self.dlg.shape_file.isValid():
                    raise QgsProcessingException(self.tr('Unvalid vector layer!'))
            elif self.dlg.refPixel_method == 1 or self.dlg.refPixel_method == 2:
                if self.dlg.input_raster_layer.source() == self.dlg.ref_image_path:
                    raise QgsProcessingException(self.tr('Unvalid reference image: Reference image can not be the same as the input raster layer.'))
                if self.dlg.input_raster_layer.source() == self.dlg.ref_pixel_maks_path:
                    raise QgsProcessingException(self.tr('Unvalid reference mask: Reference mask can not be the same as the input raster layer.'))
                if self.dlg.ref_image_path == self.dlg.ref_pixel_maks_path:
                    raise QgsProcessingException(self.tr('Reference image and reference mask can not be the same.'))

            print('Input raster source: ', self.dlg.input_raster_layer.source())
            print('Ref image file: ', self.dlg.ref_image_path)


            #run_segmentation_task(param = self.dlg)
            task = SegmentationTask(param = self.dlg)  
            self.active_tasks.append(task)  
            # NOTE: We need to keep a reference to task, otherwise is garbaged collected and the 
            # 'SegmentationTask.finished' function is not executed
            QgsApplication.taskManager().addTask(task)

            # TODO: Connect to the signals to update the UI:
            # self.task.progress_signal.connect(lambda value: self.update_progress_ui(value))
            # self.task.finished_signal.connect(lambda result: self.handle_segmentation_result(result))
            #
       

            print('Finish main segmentation')
