# -*- coding: utf-8 -*-

"""
/***************************************************************************
 SDUAgriculture
                                 A QGIS plugin
 A plugin for all SDUs Agriculture QGIS tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-05
        copyright            : (C) 2025 by SDU
        email                : hde@mmmi.sdu.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'SDU'
__date__ = '2025-02-05'
__copyright__ = '(C) 2025 by SDU'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import CDC

import numpy as np
import threading
import rasterio
from rasterio.enums import Resampling

import concurrent.futures

from qgis import processing

import os
from pathlib import Path 
import inspect
from qgis.PyQt.QtGui import QIcon

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessingAlgorithm,
                       QgsProcessingParameterBoolean,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterNumber,
                       QgsProcessingParameterEnum,
                       QgsProcessingParameterBand,
                       QgsProcessingParameterString,
                       QgsProcessingParameterFile)

from .AgroTool_ColorSegmenter_dialog import AgroTool_ColorSegmenterDialog

class SDUAgricultureAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    BANDS = "BANDS"
    REF_TYPE = "REF_TYPE"
    REFERENCE = "REFERENCE"
    ANNOTATED = "ANNOTATED"
    SHAPE_FILE = "SHAPE_FILE"
    SCALE = "SCALE"
    TILE_WIDTH = "TILE_WIDTH"
    TILE_HEIGHT = "TILE_HEIGHT"
    COLOR_MODEL = "COLOR_MODEL"
    GMM_PARAM = "GMM_PARAM"

    # NOTE: Missing params:
    TRANSFORM = "TRANSFORM"
    LAMBDA = "LAMBDA"
    GAMMA = "GAMMA"

    # NOTE: Added params
    CONVERT_UINT = "CONTERT_UINT"
    SAVE_TILES_PATH = "SAVE_TILES_PATH"
    SAVE_TILES = "SAVE_TILES"   # Bool - save images
    SAVE_TILES_DISTANCE = "SAVE_TILES_DISTANCE"     # Bool - save distan image

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        self.ref_type_choices = ["Shape File", "Reference Images"]
        self.color_model_choices = ["Mahalanobis", "Gaussian Mixture Model"]
        self.transform_choices = ["No transform", "Lambda expression", "Gamma"]
        
        
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.INPUT,
                self.tr('Input layer')
            )
        )
        self.addParameter(
             QgsProcessingParameterBand(
                  self.BANDS,
                  self.tr("Bands to use for Color"),
                  allowMultiple=True,
                  parentLayerParameterName=self.INPUT,
                  optional=True
             )
        )

        self.addParameter(
             QgsProcessingParameterEnum(
                  self.REF_TYPE,
                  self.tr("Reference type"),
                  self.ref_type_choices,
                  allowMultiple=False,
                  defaultValue=0
             )
        )
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.REFERENCE,
                self.tr("Reference Image"),
                optional=True
            )
        )
        self.addParameter(
            QgsProcessingParameterRasterLayer(
                self.ANNOTATED,
                self.tr("Reference Image Annotated"),
                optional=True
            )
        )
        self.addParameter(
             QgsProcessingParameterFeatureSource(
                  self.SHAPE_FILE,
                  self.tr("Shape file"),
                  optional=True
             )
        )

        self.addParameter(
             QgsProcessingParameterEnum(
                  self.COLOR_MODEL,
                  self.tr("Color Model"),
                  self.color_model_choices,
                  allowMultiple=False,
                  defaultValue=0
             )
        )
        self.addParameter(
             QgsProcessingParameterNumber(
                  self.GMM_PARAM,
                  self.tr("GMM parameters"),
                  type=QgsProcessingParameterNumber.Integer,
                  defaultValue=2,
                  optional=True
             )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.SCALE,
                self.tr("Scale"),
                type=QgsProcessingParameterNumber.Double,
                defaultValue=5,
                minValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.TILE_WIDTH,
                self.tr("Tile Width"),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=2048,
                minValue=64
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.TILE_HEIGHT,
                self.tr("Tile Height"),
                type=QgsProcessingParameterNumber.Integer,
                defaultValue=2048,
                minValue=64
            )
        )


        self.addParameter(
             QgsProcessingParameterEnum(
                  self.TRANSFORM,
                  self.tr("Transform to apply to input"),
                  self.transform_choices,
                  allowMultiple=False,
                  defaultValue=0
             )
        )
        self.addParameter(
             QgsProcessingParameterString(
                  self.LAMBDA,
                  self.tr("Python Lambda Expression"),
                  optional=True
             )
        )
        self.addParameter(
             QgsProcessingParameterNumber(
                  self.GAMMA,
                  self.tr("Gamma value for the gamma transform"),
                  type=QgsProcessingParameterNumber.Double,
                  defaultValue=0.5,
                  minValue=0,
                  maxValue=5,
                  optional=True
             )
        )

        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT,
                self.tr('Output Color Distance Layer')
            )
        )

        self.addParameter(QgsProcessingParameterFile(
            self.SAVE_TILES_PATH,
             self.tr('Path to save result tiles'),
            optional=True
        ))

        self.addParameter(QgsProcessingParameterBoolean(
            self.SAVE_TILES,
             self.tr('Save tiles images'),
            defaultValue=False
        ))

        self.addParameter(QgsProcessingParameterBoolean(
            self.SAVE_TILES_DISTANCE,
             self.tr('Save tiles distance images'),
            defaultValue=False
        ))

        self.addParameter(QgsProcessingParameterBoolean(
            self.CONVERT_UINT,
             self.tr('Convert result to uint8'),
            defaultValue=True
        ))

    
    def prepareAlgorithm(self, parameters, context, feedback):
        # pre process some 
        self.raster_input = self.parameterAsRasterLayer(parameters, self.INPUT, context)
        self.raster_bands = self.parameterAsInts(parameters, self.BANDS, context)
        
        print("Input params: ", parameters)
        print("input layer: ", type(self.raster_input))
        if not self.raster_bands:
            self.raster_bands = None
        else:
            self.raster_bands = [x - 1 for x in self.raster_bands]

       
        self.scale = self.parameterAsDouble(parameters, self.SCALE, context)
        tile_width = self.parameterAsInt(parameters, self.TILE_WIDTH, context)
        tile_height = self.parameterAsInt(parameters, self.TILE_HEIGHT, context)
        self.transform = self.parameterAsEnum(parameters, self.TRANSFORM, context)
        
        if self.transform == 0:
            self.transform = None
        elif self.transform == 1:
            lambda_exp = self.parameterAsString(parameters, self.LAMBDA, context)
            self.transform = CDC.LambdaTransform(lambda_exp)
        elif self.transform == 2:
            gamma = self.parameterAsDouble(parameters, self.GAMMA, context)
            self.transform = CDC.GammaTransform(gamma)

        self.ref_type = self.parameterAsEnum(parameters, self.REF_TYPE, context)
        self.color_model_params = self.parameterAsEnum(parameters, self.COLOR_MODEL, context)
        self.gmm_params = self.parameterAsInt(parameters, self.GMM_PARAM, context)

        tiler_params = {
            "orthomosaic": self.raster_input.source(),
            "tile_size": (tile_width, tile_height),
        }
        self.tiler = CDC.OrthomosaicTiles(**tiler_params)

        # NOTE: Added
        self.save_tiles_path = self.parameterAsFile(parameters, self.SAVE_TILES_PATH, context)
        self.save_tiles = self.parameterAsBoolean(parameters, self.SAVE_TILES, context)
        self.save_tiles_distance = self.parameterAsBoolean(parameters, self.SAVE_TILES_DISTANCE, context)
        self.convert_uint8 = self.parameterAsBoolean(parameters, self.CONVERT_UINT, context)

        return super().prepareAlgorithm(parameters, context, feedback)


    def processAlgorithm(self, parameters, context, feedback):

        raster_output = self.parameterAsOutputLayer(parameters, self.OUTPUT, context)

        # NOTE: Changed index here - for me shape_file = 0 , reference image = 1
        if self.ref_type == 1:
            # load reference and annotated image for color_model
            reference = self.parameterAsRasterLayer(parameters, self.REFERENCE, context)
            annotated = self.parameterAsRasterLayer(parameters, self.ANNOTATED, context)
            color_params = {
                "reference": reference.source(),
                "annotated": annotated.source(),
                "bands_to_use": self.raster_bands,
                "transform": self.transform
            }
            if self.color_model_params == 0:
                color_model = CDC.MahalanobisDistance.from_image_annotation(**color_params)
            elif self.color_model_params == 1:
                color_params.update({"n_components": self.gmm_params})
                color_model = CDC.GaussianMixtureModelDistance.from_image_annotation(**color_params)    
        elif self.ref_type == 0:
            # convert shape file polygons to point centered af pixels
            pixel_centroids_params = {
                'INPUT_RASTER': self.raster_input.source(),
                'INPUT_VECTOR': parameters[self.SHAPE_FILE],
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
            pixel_centroids = processing.run(
                "native:generatepointspixelcentroidsinsidepolygons", 
                pixel_centroids_params, 
                context=context,
                feedback=feedback,
                is_child_algorithm=True
            )
            # Sample input rasters pixel values at each point
            pixel_values_params = {
                'INPUT':pixel_centroids['OUTPUT'],
                'RASTERCOPY':self.raster_input.source(),
                'OUTPUT':'TEMPORARY_OUTPUT'
            }
            pixel_values = processing.run(
                "native:rastersampling",
                pixel_values_params,
                context=context,
                feedback=feedback,
                is_child_algorithm=True)
            # convert qgis feature to numpy array of pixel values
            pixel_values = self.parameterAsSource(pixel_values, "OUTPUT", context)
            pixel_values_list = []
            for x in pixel_values.getFeatures():
                pixel_values_list.append(x.attributes())
            pixel_value = np.array(pixel_values_list).transpose()
            pixel_value = pixel_value[3:,:]
            color_params = {
                "pixel_values": pixel_value,
                "bands_to_use": self.raster_bands,
                "transform": self.transform
            }
            if self.color_model_params == 0:
                color_model = CDC.MahalanobisDistance.from_pixel_values(**color_params)
            elif self.color_model_params == 1:
                color_params.update({"n_components": self.gmm_params})
                color_model = CDC.GaussianMixtureModelDistance.from_pixel_values(**color_params)

        # Tile orthomosaic and run in threads
        self.tiler.divide_orthomosaic_into_tiles()
        if feedback.isCanceled():
            return {}
        total = 100.0 / len(self.tiler.tiles)
        read_lock = threading.Lock()
        process_lock = threading.Lock()
        write_lock = threading.Lock()
        with rasterio.open(self.raster_input.source()) as src:
            profile = src.profile
            profile["count"] = 1

            # Save result as float64:
            if not self.convert_uint8:
                profile.update(dtype="float64")

            overview_factors = src.overviews(src.indexes[0])
            with rasterio.open(raster_output, "w", **profile) as dst:
                
                def process(tile: CDC.Tile) -> None:
                    with read_lock:
                        img = src.read(window=tile.window_with_overlap)
                        mask_temp = src.read_masks(window=tile.window_with_overlap)
                    mask = mask_temp[0]
                    for band in range(mask_temp.shape[0]):
                        mask = mask & mask_temp[band]
                    with process_lock:
                        distance_image = color_model.calculate_distance(img)
                    # scale image and convert to uint8
                    if self.convert_uint8:
                        distance = np.minimum(np.abs(self.scale * distance_image), 255)
                        distance = distance.astype(np.uint8)
                    else:
                        distance = distance_image

                    output = tile.get_window_pixels(distance)
                    mask = tile.get_window_pixels(np.expand_dims(mask, 0)).squeeze()
                    with write_lock:
                        dst.write(output, window=tile.window)
                        dst.write_mask(mask, window=tile.window)

                    # Save tiles images:
                    if self.save_tiles:
                        save_path = Path(os.path.join(self.save_tiles_path,"images"))
                        os.makedirs(save_path, exist_ok = True)
                        tile.save_tile(img, mask, save_path)
                    if self.save_tiles_distance:
                        save_path = Path(os.path.join(self.save_tiles_path,"distance"))
                        os.makedirs(save_path, exist_ok = True)
                        tile.save_tile(distance, mask, save_path)

                with concurrent.futures.ThreadPoolExecutor(max_workers=context.maximumThreads()) as executor:
                    for current, _ in enumerate(executor.map(process, self.tiler.tiles)):
                        if feedback.isCanceled():
                            return {}
                        feedback.setProgress(int(current * total))
        with rasterio.open(raster_output, "r+") as dst:
            dst.build_overviews(overview_factors, Resampling.average)
        #feedback.setProgress(100)
        # return the color distance raster.
        print("Algorithm DONE!")
        print("Result type is ", type(raster_output))
       
        return {self.OUTPUT: raster_output}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'color_distance_calculator'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr("Color Distance Calculator")

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Raster layer tools'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SDUAgricultureAlgorithm()
    
    def createCustomParametersWidget(self, parents):
        return AgroTool_ColorSegmenterDialog(alg= self, parent=parents) 

    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'icon.png')))
        return icon

