# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AgroTool_ColorSegmenter
                                 A QGIS plugin
 Precision agriculture application. This plug-in segments the raster layer based on a color distribution calculated from a shape file or a cropped image over the raster layer. (In development)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Syddansk Universitet
        email                : aqu@mmmi.sdu.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDialog
from qgis.core import QgsRasterLayer, QgsProcessingException, QgsApplication, QgsProject, QgsTask, QgsMessageLog, Qgis, QgsProcessingContext, QgsProcessingFeedback
from osgeo import gdal
from PyQt5.QtCore import QThreadPool, pyqtSignal

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .AgroTool_ColorSegmenter_dialog import AgroTool_ColorSegmenterDialog
from .AgroTool_ColorSegmenter_algorithm import SDUAgricultureAlgorithm

from .AgroTool_ColorSegmenter_provider import  SDUAgricultureProvider

import os.path
import time
import sys
import inspect
import numpy as np
from qgis import processing

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

from .Segmenter.main import SegmentationTask


class AgroTool_ColorSegmenter:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'AgroTool_ColorSegmenter_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&AgroTool Color Segmenter')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        self.active_tasks = []

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('AgroTool_ColorSegmenter', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        #icon_path = ':/plugins/AgroTool_ColorSegmenter/icon.png'
        icon_path = os.path.join(os.path.join(cmd_folder, 'icon.png'))
        #icon_path = ':\plugins\\agrotool_colorsegmenter\icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'AgroTool Color Segmenter'),
            callback=self.run_color_segmeneter,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

        # Init provider:
        self.provider = SDUAgricultureProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)



    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&AgroTool Color Segmenter'),
                action)
            self.iface.removeToolBarIcon(action)

        # Remove provider:
        QgsApplication.processingRegistry().removeProvider(self.provider)

    def run_color_segmeneter(self):
        """Run method that performs all the real work"""
        
        # from .AgroTool_ColorSegmenter_algorithm import SDUAgricultureAlgorithm

        # alg = SDUAgricultureAlgorithm()
        # dialog = alg.createCustomParametersWidget(parent=self.iface.mainWindow())

        # # Show GUI:
        # dialog.exec_()

        from .AgroTool_ColorSegmenter_dialog import AgroTool_ColorSegmenterDialog

        self.dlg = AgroTool_ColorSegmenterDialog()


        #processing.run("SDU:color_distance_calculator", parameters = {})
       