# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AgroTool_ColorSegmenterDialog
                                 A QGIS plugin
 Precision agriculture application. This plug-in segments the raster layer based on a color distribution calculated from a shape file or a cropped image over the raster layer. (In development)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Syddansk Universitet
        email                : aqu@mmmi.sdu.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox
from PyQt5.QtCore import pyqtSignal, QObject
from qgis.core import QgsProject, QgsVectorLayer, QgsRasterLayer

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ColorSegmenter_progressbar.ui'))


class GUI_signals(QObject):
    
    cancel_singal = pyqtSignal()

    def __init__(self):
        super().__init__()

class AgroTool_ColorSegmenterProgressBar(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(AgroTool_ColorSegmenterProgressBar, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        self.progressBar.setValue(0)

       
        self.singnal = GUI_signals()

        # Handle task cancellation
        self.CancelButton.clicked.connect(self.on_cancel)

        
    
    def on_cancel(self):
        # Call the cancellation method of your task.
        self.singnal.cancel_singal.emit()
        print('Button pressed')
        #self.close()  # Optionally close the progress dialog