# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AgroTool_ColorSegmenterDialog
                                 A QGIS plugin
 Precision agriculture application. This plug-in segments the raster layer based on a color distribution calculated from a shape file or a cropped image over the raster layer. (In development)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-18
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Syddansk Universitet
        email                : aqu@mmmi.sdu.dk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog, QMessageBox
from qgis.core import (QgsProject,
                      QgsVectorLayer,
                      QgsRasterLayer,
                      QgsProcessingException,
                      QgsProcessingContext,
                      QgsProcessingFeedback,
                      QgsMessageLog,
                      QgsApplication,
                      QgsTask,
                      Qgis)

from sdu_agro_tools.progressbar_dialog import AgroTool_ColorSegmenterProgressBar

class SDUAgricultureAlgorithmTask(QgsTask):
    """
    Auxiliary class - wraps the algorithm in a QTask object which allows concurrent execution
    and does not block the main QGIS thread.

    Add OUTPUT to current QGIS project - need to do manually this with custom GUI

    When you have a custom GUI, the execution of the algorithm must be done with this class:

    task = MyProcessingTask(alg = self.alg, params = params)
    self.active_task.append(task) -> Need to keep a reference to the task
    QgsApplication.instance().taskManager().addTask(task)

    """
    def __init__(self, alg, params, context, feedback):
        super().__init__('SDUAgricultureAlgorithmTask', QgsTask.CanCancel)
        # Clonamos el algoritmo para no tocar el original
        print("Init task")
        self.alg = alg #.clone()
        self.params = params
        if context is None:
            self.context = QgsProcessingContext()
            self.context.setProject(QgsProject.instance())
        else:
            self.context = context
        
        if feedback is None:
            self.feedback = QgsProcessingFeedback()
        else:
            self.feedback = feedback

        # Progress bar:
        self.progressDlg = AgroTool_ColorSegmenterProgressBar()  # a custom QDialog subclass with a QProgressBar
        self.progressDlg.setWindowTitle("AgroTool Color Segmenter-processing")
        self.progressDlg.show()

        # Progress bar feedback
        self.feedback.progressChanged.connect(lambda progress: self.progressDlg.progressBar.setValue(int(progress)))
        self.progressDlg.singnal.cancel_singal.connect(self.feedback.cancel)
        self.progressDlg.singnal.cancel_singal.connect(self.cancel)

        # Prepares the algorithm for execution - run in main thread
        self.alg.prepare(self.params, self.context, self.feedback)


    def run(self):

        print("Start running task")
        try:
            # Runs the algorithm - run in background thread
            results = self.alg.runPrepared(self.params, self.context, self.feedback)
            
            if self.feedback.isCanceled():
                return False
        
            # Save result
            self._results = results
            print("Result saved!")
            return True

        except Exception as e:
            QgsMessageLog.logMessage("Error during color segmenetation: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
            return False

    def finished(self, result):
        # Cleaning and results in the main thread
        final = self.alg.postProcess(self.context, self.feedback)

        if result:
            try:
                # Add output raster to current project
                print("Attempt to add layer")
                name = os.path.splitext(os.path.basename(self._results["OUTPUT"]))[0]
                layer = QgsRasterLayer(self._results["OUTPUT"], name)

                if not layer.isValid():
                    QgsMessageLog.logMessage("Failed to load raster output layer", "AgroTool", Qgis.Critical)
                else:
                    QgsProject.instance().addMapLayer(layer)
                
                QgsMessageLog.logMessage("Added raster layer to current project", "AgroTool Color Segmenter", level=Qgis.Info)
            except Exception as e:
                QgsMessageLog.logMessage("Error while saving result: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
        else:
            if self.feedback.isCanceled():
                QgsMessageLog.logMessage("Segmentation task cancelled.", "AgroTool Color Segmenter", level=Qgis.Critical)
            else:
                QgsMessageLog.logMessage("Segmentation task failed.", "AgroTool Color Segmenter", level=Qgis.Critical)
            
            # Delete output file:
            try:
                if os.path.exists(self.params["OUTPUT"]):
                    os.remove(self.params["OUTPUT"])
            except Exception as e:
                QgsMessageLog.logMessage("Error while deleting result: " + str(e), "AgroTool Color Segmenter", level=Qgis.Critical)
          
            

        self.progressDlg.close()

############## GRAPHIC USER INTERFACE ##############

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'AgroTool_ColorSegmenter_dialog_base.ui'))


class AgroTool_ColorSegmenterDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, alg, parent=None, context = None, feedback = None):
        """Constructor."""
        super(AgroTool_ColorSegmenterDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.ok = True # Bool determin if sucess in GUI

        # Algorithm to run:
        self.alg = alg
        self.active_task = []
        self.context = context
        self.feedback = feedback

        # Initialize default values of parameters:
        self.setParameters()

        # Connect signals
        ############ INPUT RASTER LAYER ############
        # Connect the combo box and button to methods
        self.InputRasterLayerSelector.currentIndexChanged.connect(self.select_input_raster_layer)
        self.InputRasterLayerButton.clicked.connect(self.load_input_aster_layer)

        ############ OUTPUT RASTER ############
        self.OutputRasterButton.clicked.connect(self.select_output_file)

        ########### CONVERT UINT8 #############
        self.ConvertScaleCheckBox.stateChanged.connect(self.convert_scale_checkbox)
    
        ############ REF. PIXEL TAB SELECTION ############
        self.refPixel_tab.currentChanged.connect(self.refPixel_selector)

        # Connect ShapeFile Widget
        # Connect the combo box and button to methods
        self.InputShapeFileSelector.currentIndexChanged.connect(self.shapefile_selector)
        self.ShapeFileButton.clicked.connect(self.load_shapefile)


        # Connect Image Widget
        self.ImageFormatSelector.currentIndexChanged.connect(self.image_format_selector)

        # Connect the combo box and button to methods
        self.ReferenceImageSelector.currentIndexChanged.connect(self.refimage_selector)
        self.ReferenceImageButton.clicked.connect(self.load_refimage)

        self.ReferenceMaskSelector.currentIndexChanged.connect(self.refmask_selector)
        self.ReferenceMaskButton.clicked.connect(self.load_maskimage)

        ############ METRIC SELECTION ############
        self.GMMSpinBox.setEnabled(False)   # As default is Mahalanobis, number of component of GMM is desable initially
        self.MetricSelector.currentIndexChanged.connect(self.metric_selector)

        ############ TILE PROCESSING ############
        self.TilesProcessingCheckBox.stateChanged.connect(self.tiles_processing_checkbox)
        self.SaveTilesCheckBox.stateChanged.connect(self.save_tiles_checkbox)
        self.SaveTilesDistanceCheckBox.stateChanged.connect(self.save_distance_tiles_checkbox)
        self.SaveTilesButton.setEnabled(False)
        self.SaveTilesLineEdit.setEnabled(False)
        self.SaveTilesButton.clicked.connect(self.select_tiles_output_dir)


    def setParameters(self, parameters: dict = None):
        """
        Funciton that initialize Widget with default parameters values.
        Needed to execute processing.execAlgorithmDialog
        """
        if parameters is None:
             # TODO: Include band and overlap in GUI
            # Parameters:
            self.input_raster_layer = None
            self.output_file_path = None
            self.refPixel_method = 0 # 0: ShapeFile, 1: Image .tiff, 2: Image .jpg
            self.shape_file = None
            self.ref_image_path = None
            self.ref_pixel_maks_path = None
            self.distance_metric = 'Mahalanobis'
            self.gmm_components = 2
            self.convert_uint8 = True  
            self.scale_factor = 5
            self.bands_to_use = [] 
            self.tile_processing = True
            self.tiles_width = 3000
            self.tiles_height = 3000
            self.save_tiles_path = None
            self.save_tiles = False
            self.save_tiles_distance = False
            self.overlap = 0.01    # NOTE: Need to be added to GUI

            self.parameters = {
                    'INPUT': self.input_raster_layer,
                    'OUTPUT': self.output_file_path,
                    'REF_TYPE': self.refPixel_method,
                    'SHAPE_FILE': self.shape_file,
                    'REFERENCE': self.ref_image_path,
                    'ANNOTATED': self.ref_pixel_maks_path,
                    'COLOR_MODEL': self.distance_metric,
                    'GMM_PARAM': self.gmm_components,
                    'CONTERT_UINT': self.convert_uint8,
                    'SCALE': self.scale_factor,
                    'BANDS': self.bands_to_use,
                    'tile_processing': self.tile_processing,
                    'TILE_WIDTH': self.tiles_width,
                    'TILE_HEIGHT': self.tiles_height,
                    'SAVE_TILES_PATH': self.save_tiles_path,
                    'SAVE_TILES': self.save_tiles,
                    'SAVE_TILES_DISTANCE': self.save_tiles_distance,
                    #'overlap': self.overlap,
                }
        else:
            self.parameters = parameters
        
    def results(self):
        """"
        Function that returns whether the GUI process has been successful
        Needed to execute processing.execAlgorithmDialog  
        """
        return self.ok
        
    def showEvent(self, event):
        """Override the showEvent to refresh available layers when the GUI is opened."""
        super().showEvent(event)  # Call the parent class's showEvent method

        # Refresh the combo boxes here
        self.update_layers(clear_output = True)
        self.refPixel_selector(self.refPixel_tab.currentIndex())

    def validate_and_accept(self):
        " Function to validate all parameters are loaded correctly"
        self.ok = True

        # Input layer:
        self.select_input_raster_layer()
        if self.input_raster_layer == None:
            self.ok = False
            QMessageBox.warning(self, "Missing input raster", "Please load a valid input raster layer.")

        # Output file:
        if self.output_file_path == None:
            self.ok = False
            QMessageBox.warning(self, "Missing output file", "Please select a valid output file.")

        # Convert to uint8:
        self.convert_uint8 = self.ConvertScaleCheckBox.isChecked()
        if self.convert_uint8:
            self.scale_factor = self.ScaleFactorSpinBox.value()
        else:
            self.scale_factor = None

        # Reference pixel selector:
        self.refPixel_selector(self.refPixel_tab.currentIndex())

        if self.refPixel_method == 0:
            self.shapefile_selector()
            if self.shape_file == None:
                self.ok = False
                QMessageBox.warning(self, "Missing shape file", "Please seled a valid shape file.")

        elif self.refPixel_method == 1 or self.refPixel_method == 2:
            self.refimage_selector()
            if self.ref_image_path == None:
                self.ok = False
                QMessageBox.warning(self, "Missing reference image", "Please seled a valid reference image (.tiff or .jpg)")

            self.refmask_selector()
            if self.ref_pixel_maks_path == None:
                self.ok = False
                QMessageBox.warning(self, "Missing reference mask", "Please seled a valid reference mask (.tiff or .jpg)")

        # Distance metric:
        self.distance_metric = self.MetricSelector.currentText()
        
        # Band to use:
        if self.R_button.isChecked():
            self.bands_to_use.append(1)
        if self.G_button.isChecked():
            self.bands_to_use.append(2)
        if self.B_button.isChecked():
            self.bands_to_use.append(3)

        #self.scale_factor_selector = self.ScaleFactorSpinBox.value()
        if self.distance_metric == 'Gaussian Mixture Model':
            self.gmm_components = self.GMMSpinBox.value()

        # Map distance name to numbers:
        # Remap color model:
        if self.distance_metric == "Mahalanobis":
            self.distance_metric = 0
        elif self.distance_metric == "Gaussian Mixture Model":
            self.distance_metric = 1
        else:
            raise Exception
        
        # Tiles processing:
        self.tile_processing = self.TilesProcessingCheckBox.isChecked()
        if self.tile_processing:
            self.tiles_width = self.TilesWidthSpinBox.value()
            self.tiles_height = self.TilesHeigthSpinBox.value()

            self.save_tiles = self.SaveTilesCheckBox.isChecked()
            self.save_tiles_distance = self.SaveTilesDistanceCheckBox.isChecked()

            if self.save_tiles or self.save_tiles_distance:
                if self.save_tiles_path == None:
                    self.ok = False
                    QMessageBox.warning(self, "Missing directory", "Please select a valid directory to save the tiles.")
        else:
            self.save_tiles = False
            self.save_tiles_distance = False

         # Verify if valid raster layer
        if not self.input_raster_layer.isValid():
            self.ok = False
            raise QgsProcessingException('Unvalid input raster layer.')

        if self.refPixel_method == 0:
            if not self.shape_file.isValid():
                self.ok = False
                raise QgsProcessingException('Unvalid vector layer!')
        elif self.refPixel_method == 1 or self.refPixel_method == 2:
            if self.input_raster_layer.source() == self.ref_image_path:
                self.ok = False
                raise QgsProcessingException('Unvalid reference image: Reference image can not be the same as the input raster layer.')
            if self.input_raster_layer.source() == self.ref_pixel_maks_path:
                self.ok = False
                raise QgsProcessingException('Unvalid reference mask: Reference mask can not be the same as the input raster layer.')
            if self.ref_image_path == self.ref_pixel_maks_path:
                self.ok = False
                raise QgsProcessingException('Reference image and reference mask can not be the same.')

        # Close GUI and start execution
       
        if self.ok:
            super().accept()

            # Parameter dict map:
            self.params = {
                'INPUT': self.input_raster_layer,
                'OUTPUT': self.output_file_path,
                'REF_TYPE': self.refPixel_method,
                'SHAPE_FILE': self.shape_file,
                'REFERENCE': self.ref_image_path,
                'ANNOTATED': self.ref_pixel_maks_path,
                'COLOR_MODEL': self.distance_metric,
                'GMM_PARAM': self.gmm_components,
                'CONTERT_UINT': self.convert_uint8,
                'SCALE': self.scale_factor,
                'BANDS': self.bands_to_use,
                'tile_processing': self.tile_processing,
                'TILE_WIDTH': self.tiles_width,
                'TILE_HEIGHT': self.tiles_height,
                'SAVE_TILES_PATH': self.save_tiles_path,
                'SAVE_TILES': self.save_tiles,
                'SAVE_TILES_DISTANCE': self.save_tiles_distance,
                #'overlap': self.overlap,
            }

            try:
                # Init algorithm as a QTask
                task = SDUAgricultureAlgorithmTask(alg = self.alg, params = self.params, context = self.context, feedback = self.feedback)
                self.active_task.append(task)
                QgsApplication.instance().taskManager().addTask(task)
            except Exception as e:
                raise e
            
       


    def update_layers(self, clear_output = False):
        layers = QgsProject.instance().mapLayers().values()

        # Input raster
        self.InputRasterLayerSelector.blockSignals(True)
        current_raster = self.InputRasterLayerSelector.currentText()  # Save the current selection before clearing
        self.InputRasterLayerSelector.clear()
        # Populate the comboBox with names of all the loaded layers
        raster_layers_names = [layer.name() for layer in layers if isinstance(layer, QgsRasterLayer) and layer.source().lower().endswith('.tif')]
        self.InputRasterLayerSelector.addItems(raster_layers_names)
        if current_raster in raster_layers_names:
            self.InputRasterLayerSelector.setCurrentText(current_raster) # Load the current selection if there was any
        self.InputRasterLayerSelector.blockSignals(False)

        # Shape file
        self.InputShapeFileSelector.blockSignals(True)
        current_shape = self.InputShapeFileSelector.currentText()  # Save the current selection before clearing
        self.InputShapeFileSelector.clear()
        # Populate the comboBox with names of all the loaded layers
        shape_files_names = [layer.name() for layer in layers if isinstance(layer, QgsVectorLayer) and layer.providerType() == "ogr"]
        self.InputShapeFileSelector.addItems(shape_files_names)
        if current_shape in shape_files_names:
            self.InputShapeFileSelector.setCurrentText(current_shape) # Load the current selection if there was any
        self.InputShapeFileSelector.blockSignals(False)

        # Image format
        image_format = self.ImageFormatSelector.currentText()
        print('IMAGE FORMAT', image_format)
        self.ReferenceImageSelector.blockSignals(True)
        current_ref_image = self.ReferenceImageSelector.currentText()  # Save current selections
        current_ref_mask = self.ReferenceMaskSelector.currentText()
        self.ReferenceMaskSelector.blockSignals(True)
        self.ReferenceImageSelector.clear()
        self.ReferenceMaskSelector.clear()
        tiff_layers_names = []
        jpg_layers_names = []
        if image_format == '.tiff':
            # Populate the comboBox with names of all the loaded layers
            tiff_layers_names = [layer.name() for layer in layers if isinstance(layer, QgsRasterLayer) and layer.source().lower().endswith('.tif')]
            self.ReferenceImageSelector.addItems(tiff_layers_names)
            self.ReferenceMaskSelector.addItems(tiff_layers_names)
        elif image_format == '.jpg':
            # Populate the comboBox with names of all the loaded layers
            jpg_layers_names = [layer.name() for layer in layers if isinstance(layer, QgsRasterLayer) and (layer.source().lower().endswith('.jpg') or layer.source().lower().endswith('.jpeg'))]
            self.ReferenceImageSelector.addItems(jpg_layers_names)
            self.ReferenceMaskSelector.addItems(jpg_layers_names)
        # Restore the selections if they exist in the new lists
        if current_ref_image in tiff_layers_names or current_ref_image in jpg_layers_names:
            self.ReferenceImageSelector.setCurrentText(current_ref_image)
        if current_ref_mask in tiff_layers_names or current_ref_mask in jpg_layers_names:
            self.ReferenceMaskSelector.setCurrentText(current_ref_mask)
        self.ReferenceImageSelector.blockSignals(False)
        self.ReferenceMaskSelector.blockSignals(False)

        if clear_output:
            self.OutputRasterLineEdit.clear()
            self.SaveTilesLineEdit.clear()


    def select_input_raster_layer(self):
        """Handle changes in combo box selection."""
        # Get the currently selected layer name from the combo box
        selected_layer_name = self.InputRasterLayerSelector.currentText()

        for layer in QgsProject.instance().mapLayers().values(): #QgsProject.instance().layerTreeRoot().children():
            if isinstance(layer, QgsRasterLayer) and layer.name() == selected_layer_name:
                self.input_raster_layer = layer
                break

        # TODO: Delete following prints
        # Debugging output
        if self.input_raster_layer:
            print(f"Selected raster layer object: {self.input_raster_layer}")
        else:
            print(f"No matching input QgsRasterLayer found for: {self.input_raster_layer}")

    def load_input_aster_layer(self):
        """Opens a dialog to select a .tiff raster file and load it into QGIS"""
        # Open a file dialog to select a .tiff file
        filename, _filter = QFileDialog.getOpenFileName(self, "Select Raster File", "", "*.tif")

        # Check if the user selected a file
        if filename:
            # Create a new raster layer
            layer_name = os.path.splitext(os.path.basename(filename))[0]
            raster_layer = QgsRasterLayer(filename, layer_name)

            # Check if the layer is valid
            if not raster_layer.isValid():
                QMessageBox.warning(self, "Invalid Layer", "The selected layer is not valid.")
                return

            # Add the raster layer to the QGIS project
            QgsProject.instance().addMapLayer(raster_layer)

            # Update combo box and set the last selected layer to the new raster layer
            self.InputRasterLayerSelector.addItem(raster_layer.name(), raster_layer.id())
            self.input_raster_layer = raster_layer  # Update with the newly loaded layer
            print(f"Selected raster layer object: {self.input_raster_layer}")
            # Set combo box to the newly added layer's name
            self.InputRasterLayerSelector.setCurrentText(raster_layer.name())
            self.update_layers()
        else:
            QMessageBox.warning(self, "No File Selected", "Please select a valid .tiff file.")



    def select_output_file(self):
        filename, _filter = QFileDialog.getSaveFileName(
            self, "Select output file ","", '*.tiff')

        if filename:
            self.OutputRasterLineEdit.setText(filename)
            self.output_file_path = filename
        else:
            QMessageBox.warning(self, "No File Selected", "Please select a output file.")



    def shapefile_selector(self):
        """Handle changes in combo box selection."""
        # Get the currently selected layer name from the combo box
        selected_layer_name = self.InputShapeFileSelector.currentText()
        self.shape_file = None
        for layer in QgsProject.instance().mapLayers().values(): #QgsProject.instance().layerTreeRoot().children():
            if isinstance(layer, QgsVectorLayer) and layer.name() == selected_layer_name:
                self.shape_file = layer
                break

        # TODO: Delete following prints
        # Debugging output
        if self.shape_file:
            print(f"Selected vector layer object: {self.shape_file}")
        else:
            print(f"No matching QgsVectorLayer found for: {self.shape_file}")

    def load_shapefile(self):
        """Opens a dialog to select a .tiff raster file and load it into QGIS"""
        # Open a file dialog to select a .shp file
        filename, _filter = QFileDialog.getOpenFileName(self, "Select Shapefile", "", "Shapefiles (*.shp)")

        # Check if the user selected a file
        if filename:
            # Create a new vector layer
            layer_name = os.path.splitext(os.path.basename(filename))[0]
            vector_layer = QgsVectorLayer(filename, layer_name, "ogr")

            # Check if the layer is valid
            if not vector_layer.isValid():
                QMessageBox.warning(self, "Invalid Layer", "The selected shapefile is not valid.")
                return

            # Add the vector layer to the QGIS project
            QgsProject.instance().addMapLayer(vector_layer)

            # Update combo box and set the last selected layer to the new vector layer
            self.InputShapeFileSelector.addItem(vector_layer.name(), vector_layer.id())
            self.shape_file = vector_layer  # Update with the newly loaded layer
            print(f"Selected shapefile layer object: {self.shape_file.name()}")

            # Set combo box to the newly added layer's name
            self.InputShapeFileSelector.setCurrentText(vector_layer.name())
            self.update_layers()
        else:
            QMessageBox.warning(self, "No File Selected", "Please select a valid .shp file.")

    def image_format_selector(self):
        " This function serve a double purpose: select the image format and also update the available layer to select"
        image_format = self.ImageFormatSelector.currentText()
        if image_format == '.tiff':
            self.refPixel_method = 1
        elif image_format == '.jpg':
            self.refPixel_method = 2
        self.update_layers()

    def refimage_selector(self):
        """Handle changes in combo box selection."""
        # Get the currently selected layer name from the combo box
        selected_layer_name = self.ReferenceImageSelector.currentText()
        print('DEBUGG: ', selected_layer_name)
        self.ref_image_path = None
        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsRasterLayer) and layer.name() == selected_layer_name:
                self.ref_image_path = layer.source()
                break

        # TODO: Delete following prints
        # Debugging output
        if self.ref_image_path:
            print(f"Selected reference image object: {self.ref_image_path}")
        else:
            print(f"No matching reference image QgsRasterLayer found for: {self.ref_image_path}")

    def refmask_selector(self):
        """Handle changes in combo box selection."""
        # Get the currently selected layer name from the combo box
        selected_layer_name = self.ReferenceMaskSelector.currentText()
        self.ref_pixel_maks_path = None
        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsRasterLayer) and layer.name() == selected_layer_name:
                self.ref_pixel_maks_path = layer.source()
                break

        # TODO: Delete following prints
        # Debugging output
        if self.ref_pixel_maks_path:
            print(f"Selected reference mask object: {self.ref_pixel_maks_path}")
        else:
            print(f"No matching mask QgsRasterLayer found for: {self.ref_pixel_maks_path}")

    def load_refimage(self):
        """Opens a dialog to select a .tiff raster file and load it into QGIS"""
        # Open a file dialog to select a .tiff file
        if self.refPixel_method == 1:
            filename, _filter = QFileDialog.getOpenFileName(self, "Select Reference Image", "", "*.tif")
        elif self.refPixel_method == 2:
            filename, _filter = QFileDialog.getOpenFileName(self, "Select Reference Image", "", "*.jpg *.jpeg")

        # Check if the user selected a file
        if filename:
            # Create a new raster layer
            layer_name = os.path.splitext(os.path.basename(filename))[0]
            ref_image = QgsRasterLayer(filename, layer_name)

            # Check if the layer is valid
            if not ref_image.isValid():
                QMessageBox.warning(self, "Invalid Layer", "The selected layer is not valid.")
                return

            # Add the raster layer to the QGIS project
            QgsProject.instance().addMapLayer(ref_image)

            # Update combo box and set the last selected layer to the new raster layer
            self.ReferenceImageSelector.addItem(ref_image.name(), ref_image.id())
            self.ref_image_path = ref_image.source()  # Update with the newly loaded layer
            print(f"Selected raster layer object: {self.ref_image_path}")
            # Set combo box to the newly added layer's name
            self.ReferenceImageSelector.setCurrentText(ref_image.name())
            self.update_layers()
        else:
            QMessageBox.warning(self, "No File Selected", "Please select a valid file.")

    def load_maskimage(self):
        """Opens a dialog to select a .tiff raster file and load it into QGIS"""
        # Open a file dialog to select a .tiff file
        if self.refPixel_method == 1:
            filename, _filter = QFileDialog.getOpenFileName(self, "Select Reference Image", "", "*.tif")
        elif self.refPixel_method == 2:
            filename, _filter = QFileDialog.getOpenFileName(self, "Select Reference Image", "", "*.jpg *.jpeg")

        # Check if the user selected a file
        if filename:
            # Create a new raster layer
            layer_name = os.path.splitext(os.path.basename(filename))[0]
            ref_image = QgsRasterLayer(filename, layer_name)

            # Check if the layer is valid
            if not ref_image.isValid():
                QMessageBox.warning(self, "Invalid Layer", "The selected layer is not valid.")
                return

            # Add the raster layer to the QGIS project
            QgsProject.instance().addMapLayer(ref_image)

            # Update combo box and set the last selected layer to the new raster layer
            self.ReferenceMaskSelector.addItem(ref_image.name(), ref_image.id())
            self.ref_pixel_maks_path = ref_image.source()  # Update with the newly loaded layer
            print(f"Selected raster layer object: {self.ref_pixel_maks_path}")
            # Set combo box to the newly added layer's name
            self.ReferenceMaskSelector.setCurrentText(ref_image.name())
            self.update_layers()
        else:
            QMessageBox.warning(self, "No File Selected", "Please select a valid file.")

    def refPixel_selector(self, index):
        """Handle tab change events."""

        if index == 0:  # Tab ShapeFie selected
            self.refPixel_method = 0

        elif index == 1:  # Tab Image selected
            image_format = self.ImageFormatSelector.currentText()
            if image_format == '.tiff':
                self.refPixel_method = 1
            elif image_format == '.jpg':
                self.refPixel_method = 2
        self.update_layers()
        print("Reference method ", self.refPixel_method)


    def metric_selector(self):
        """Handle changes in combo box selection."""
        # Get the currently selected layer name from the combo box
        selected_metric = self.MetricSelector.currentText()
        self.distance_metric = selected_metric

        if selected_metric == 'Gaussian Mixture Model':
            self.GMMSpinBox.setEnabled(True)
            self.gmm_components = self.GMMSpinBox.value()
        else:
            self.GMMSpinBox.setEnabled(False)

    def save_tiles_checkbox(self, state):
        if state == 2:
            self.save_tiles = True
            self.SaveTilesButton.setEnabled(True)
            self.SaveTilesLineEdit.setEnabled(True)
        elif state == 0:
            self.save_tiles = False

            if not self.SaveTilesDistanceCheckBox.isChecked():
                self.SaveTilesButton.setEnabled(False)
                self.SaveTilesLineEdit.setEnabled(False)

    def save_distance_tiles_checkbox(self, state):
        if state == 2:
            self.save_tiles_distance = True
            self.SaveTilesButton.setEnabled(True)
            self.SaveTilesLineEdit.setEnabled(True)
        elif state == 0:
            self.save_tiles_distance = False

            if not self.SaveTilesCheckBox.isChecked():
                self.SaveTilesButton.setEnabled(False)
                self.SaveTilesLineEdit.setEnabled(False)

    def convert_scale_checkbox(self, state):
        if state == 2:
            self.convert_uint8 = True
            self.ScaleFactorSpinBox.setEnabled(True)
        elif state == 0:
            self.convert_uint8 = False
            self.ScaleFactorSpinBox.setEnabled(False)
        
    def tiles_processing_checkbox(self, state):
        if state == 2:
            self.tile_processing = True
            self.TilesWidthSpinBox.setEnabled(True)
            self.TilesHeigthSpinBox.setEnabled(True)
            self.SaveTilesCheckBox.setEnabled(True)
            self.SaveTilesDistanceCheckBox.setEnabled(True)
            if self.SaveTilesCheckBox.isChecked() or self.SaveTilesDistanceCheckBox.isChecked():
                self.SaveTilesButton.setEnabled(True)
                self.SaveTilesLineEdit.setEnabled(True)
        elif state == 0:
            self.tile_processing = False
            self.TilesWidthSpinBox.setEnabled(False)
            self.TilesHeigthSpinBox.setEnabled(False)
            self.SaveTilesCheckBox.setEnabled(False)
            self.SaveTilesDistanceCheckBox.setEnabled(False)
            self.SaveTilesButton.setEnabled(False)
            self.SaveTilesLineEdit.setEnabled(False)

    def select_tiles_output_dir(self):
         # Open a dialog to select an existing directory
        directory = QFileDialog.getExistingDirectory(
            self, "Select Output Directory", ""
        )

        if directory:
            # Update the line edit with the selected directory path
            self.SaveTilesLineEdit.setText(directory)
            self.save_tiles_path = directory
        else:
            # Warn the user if no directory is selected
            QMessageBox.warning(self, "No Directory Selected", "Please select a valid directory.")

